# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/jeffjhzhang/pyabc/colordemo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(518, 387)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.spinred = QtWidgets.QSpinBox(Form)
        self.spinred.setMaximum(255)
        self.spinred.setObjectName("spinred")
        self.verticalLayout.addWidget(self.spinred)
        self.slidered = QtWidgets.QSlider(Form)
        self.slidered.setMinimumSize(QtCore.QSize(20, 160))
        self.slidered.setMaximum(255)
        self.slidered.setOrientation(QtCore.Qt.Vertical)
        self.slidered.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.slidered.setObjectName("slidered")
        self.verticalLayout.addWidget(self.slidered)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.spingreen = QtWidgets.QSpinBox(Form)
        self.spingreen.setMaximum(255)
        self.spingreen.setObjectName("spingreen")
        self.verticalLayout_2.addWidget(self.spingreen)
        self.slidegreen = QtWidgets.QSlider(Form)
        self.slidegreen.setMinimumSize(QtCore.QSize(20, 160))
        self.slidegreen.setMaximum(255)
        self.slidegreen.setOrientation(QtCore.Qt.Vertical)
        self.slidegreen.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.slidegreen.setObjectName("slidegreen")
        self.verticalLayout_2.addWidget(self.slidegreen)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.spinblue = QtWidgets.QSpinBox(Form)
        self.spinblue.setMaximum(255)
        self.spinblue.setObjectName("spinblue")
        self.verticalLayout_3.addWidget(self.spinblue)
        self.slideblue = QtWidgets.QSlider(Form)
        self.slideblue.setMinimumSize(QtCore.QSize(20, 160))
        self.slideblue.setMaximum(255)
        self.slideblue.setOrientation(QtCore.Qt.Vertical)
        self.slideblue.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.slideblue.setObjectName("slideblue")
        self.verticalLayout_3.addWidget(self.slideblue)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 2, 1, 1)
        self.lblcolor = QtWidgets.QLabel(Form)
        self.lblcolor.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblcolor.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblcolor.setLineWidth(1)
        self.lblcolor.setObjectName("lblcolor")
        self.gridLayout.addWidget(self.lblcolor, 1, 0, 1, 3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "red"))
        self.label_2.setText(_translate("Form", "green"))
        self.label_3.setText(_translate("Form", "blue"))
        self.lblcolor.setText(_translate("Form", "note"))
