# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/jeffjhzhang/pyabc/layouttest.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(463, 143)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(9, 9, 441, 121))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.doubleSpinBox4 = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox4.setObjectName("doubleSpinBox4")
        self.gridLayout.addWidget(self.doubleSpinBox4, 2, 2, 1, 1)
        self.doubleSpinBox6 = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox6.setObjectName("doubleSpinBox6")
        self.gridLayout.addWidget(self.doubleSpinBox6, 3, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.doubleSpinBox2 = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox2.setObjectName("doubleSpinBox2")
        self.gridLayout.addWidget(self.doubleSpinBox2, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.doubleSpinBox1 = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox1.setObjectName("doubleSpinBox1")
        self.gridLayout.addWidget(self.doubleSpinBox1, 1, 0, 1, 1)
        self.doubleSpinBox3 = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox3.setObjectName("doubleSpinBox3")
        self.gridLayout.addWidget(self.doubleSpinBox3, 2, 0, 1, 1)
        self.doubleSpinBox5 = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox5.setObjectName("doubleSpinBox5")
        self.gridLayout.addWidget(self.doubleSpinBox5, 3, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnOK = QtWidgets.QPushButton(self.widget)
        self.btnOK.setObjectName("btnOK")
        self.horizontalLayout.addWidget(self.btnOK)
        self.label_4.setBuddy(self.doubleSpinBox5)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.doubleSpinBox1, self.doubleSpinBox2)
        Form.setTabOrder(self.doubleSpinBox2, self.doubleSpinBox3)
        Form.setTabOrder(self.doubleSpinBox3, self.doubleSpinBox4)
        Form.setTabOrder(self.doubleSpinBox4, self.doubleSpinBox5)
        Form.setTabOrder(self.doubleSpinBox5, self.doubleSpinBox6)
        Form.setTabOrder(self.doubleSpinBox6, self.btnOK)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", " "))
        self.label_2.setText(_translate("Form", "收益"))
        self.label_3.setText(_translate("Form", "最大回数"))
        self.label_4.setText(_translate("Form", "&sharp比"))
        self.label_6.setText(_translate("Form", "最大值"))
        self.label_5.setText(_translate("Form", "最小值"))
        self.btnOK.setText(_translate("Form", "开始"))
