# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/jeffjhzhang/pyabc/src/pdfbkgen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PdfBkGen(object):
    def setupUi(self, PdfBkGen):
        PdfBkGen.setObjectName("PdfBkGen")
        PdfBkGen.resize(577, 158)
        PdfBkGen.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(PdfBkGen)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(PdfBkGen)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.txtpdf = QtWidgets.QLineEdit(PdfBkGen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtpdf.sizePolicy().hasHeightForWidth())
        self.txtpdf.setSizePolicy(sizePolicy)
        self.txtpdf.setMinimumSize(QtCore.QSize(340, 0))
        self.txtpdf.setObjectName("txtpdf")
        self.gridLayout.addWidget(self.txtpdf, 0, 1, 1, 1)
        self.btnpdf = QtWidgets.QPushButton(PdfBkGen)
        self.btnpdf.setObjectName("btnpdf")
        self.gridLayout.addWidget(self.btnpdf, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(PdfBkGen)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.txtbk = QtWidgets.QLineEdit(PdfBkGen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtbk.sizePolicy().hasHeightForWidth())
        self.txtbk.setSizePolicy(sizePolicy)
        self.txtbk.setMinimumSize(QtCore.QSize(340, 0))
        self.txtbk.setObjectName("txtbk")
        self.gridLayout.addWidget(self.txtbk, 1, 1, 1, 1)
        self.btnbk = QtWidgets.QPushButton(PdfBkGen)
        self.btnbk.setObjectName("btnbk")
        self.gridLayout.addWidget(self.btnbk, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnrun = QtWidgets.QPushButton(PdfBkGen)
        self.btnrun.setObjectName("btnrun")
        self.horizontalLayout.addWidget(self.btnrun)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(PdfBkGen)
        QtCore.QMetaObject.connectSlotsByName(PdfBkGen)
        PdfBkGen.setTabOrder(self.txtpdf, self.btnpdf)
        PdfBkGen.setTabOrder(self.btnpdf, self.txtbk)
        PdfBkGen.setTabOrder(self.txtbk, self.btnbk)
        PdfBkGen.setTabOrder(self.btnbk, self.btnrun)

    def retranslateUi(self, PdfBkGen):
        _translate = QtCore.QCoreApplication.translate
        PdfBkGen.setWindowTitle(_translate("PdfBkGen", "PDF Bookmark Generator"))
        self.label.setText(_translate("PdfBkGen", "PDF path"))
        self.btnpdf.setText(_translate("PdfBkGen", "Select PDF"))
        self.label_2.setText(_translate("PdfBkGen", "Bookmark path"))
        self.btnbk.setText(_translate("PdfBkGen", "Select Bookmark"))
        self.btnrun.setText(_translate("PdfBkGen", "Run"))
